// Code generated by goyacc -o generated_parser.y.go generated_parser.y. DO NOT EDIT.

//line generated_parser.y:15
package parser

import __yyfmt__ "fmt"

//line generated_parser.y:15

import (
	"math"
	"sort"
	"strconv"
	"time"

	"github.com/prometheus/prometheus/pkg/labels"
	"github.com/prometheus/prometheus/pkg/value"
)

//line generated_parser.y:28
type yySymType struct {
	yys      int
	node     Node
	item     Item
	matchers []*labels.Matcher
	matcher  *labels.Matcher
	label    labels.Label
	labels   labels.Labels
	strings  []string
	series   []SequenceValue
	uint     uint64
	float    float64
	duration time.Duration
}

const EQL = 57346
const BLANK = 57347
const COLON = 57348
const DOUBLECOLON = 57349
const COMMA = 57350
const COMMENT = 57351
const DURATION = 57352
const EOF = 57353
const ERROR = 57354
const IDENTIFIER = 57355
const LEFT_BRACE = 57356
const LEFT_BRACKET = 57357
const LEFT_PAREN = 57358
const METRIC_IDENTIFIER = 57359
const NUMBER = 57360
const RIGHT_BRACE = 57361
const RIGHT_BRACKET = 57362
const RIGHT_PAREN = 57363
const SEMICOLON = 57364
const SPACE = 57365
const STRING = 57366
const TIMES = 57367
const operatorsStart = 57368
const ADD = 57369
const DIV = 57370
const EQLC = 57371
const EQL_REGEX = 57372
const GTE = 57373
const GTR = 57374
const LAND = 57375
const LOR = 57376
const LSS = 57377
const LTE = 57378
const LUNLESS = 57379
const MOD = 57380
const MUL = 57381
const NEQ = 57382
const NEQ_REGEX = 57383
const POW = 57384
const SUB = 57385
const AT = 57386
const operatorsEnd = 57387
const aggregatorsStart = 57388
const AVG = 57389
const BOTTOMK = 57390
const COUNT = 57391
const COUNT_VALUES = 57392
const GROUP = 57393
const MAX = 57394
const MIN = 57395
const QUANTILE = 57396
const STDDEV = 57397
const STDVAR = 57398
const SUM = 57399
const TOPK = 57400
const aggregatorsEnd = 57401
const keywordsStart = 57402
const BOOL = 57403
const BY = 57404
const GROUP_LEFT = 57405
const GROUP_RIGHT = 57406
const IGNORING = 57407
const OFFSET = 57408
const ON = 57409
const WITHOUT = 57410
const keywordsEnd = 57411
const preprocessorStart = 57412
const START = 57413
const END = 57414
const preprocessorEnd = 57415
const startSymbolsStart = 57416
const START_METRIC = 57417
const START_SERIES_DESCRIPTION = 57418
const START_EXPRESSION = 57419
const START_METRIC_SELECTOR = 57420
const startSymbolsEnd = 57421

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EQL",
	"BLANK",
	"COLON",
	"DOUBLECOLON",
	"COMMA",
	"COMMENT",
	"DURATION",
	"EOF",
	"ERROR",
	"IDENTIFIER",
	"LEFT_BRACE",
	"LEFT_BRACKET",
	"LEFT_PAREN",
	"METRIC_IDENTIFIER",
	"NUMBER",
	"RIGHT_BRACE",
	"RIGHT_BRACKET",
	"RIGHT_PAREN",
	"SEMICOLON",
	"SPACE",
	"STRING",
	"TIMES",
	"operatorsStart",
	"ADD",
	"DIV",
	"EQLC",
	"EQL_REGEX",
	"GTE",
	"GTR",
	"LAND",
	"LOR",
	"LSS",
	"LTE",
	"LUNLESS",
	"MOD",
	"MUL",
	"NEQ",
	"NEQ_REGEX",
	"POW",
	"SUB",
	"AT",
	"operatorsEnd",
	"aggregatorsStart",
	"AVG",
	"BOTTOMK",
	"COUNT",
	"COUNT_VALUES",
	"GROUP",
	"MAX",
	"MIN",
	"QUANTILE",
	"STDDEV",
	"STDVAR",
	"SUM",
	"TOPK",
	"aggregatorsEnd",
	"keywordsStart",
	"BOOL",
	"BY",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"IGNORING",
	"OFFSET",
	"ON",
	"WITHOUT",
	"keywordsEnd",
	"preprocessorStart",
	"START",
	"END",
	"preprocessorEnd",
	"startSymbolsStart",
	"START_METRIC",
	"START_SERIES_DESCRIPTION",
	"START_EXPRESSION",
	"START_METRIC_SELECTOR",
	"startSymbolsEnd",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line generated_parser.y:758

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 35,
	1, 131,
	11, 131,
	23, 131,
	-2, 0,
	-1, 58,
	2, 143,
	16, 143,
	62, 143,
	68, 143,
	-2, 97,
	-1, 59,
	2, 144,
	16, 144,
	62, 144,
	68, 144,
	-2, 98,
	-1, 60,
	2, 145,
	16, 145,
	62, 145,
	68, 145,
	-2, 100,
	-1, 61,
	2, 146,
	16, 146,
	62, 146,
	68, 146,
	-2, 101,
	-1, 62,
	2, 147,
	16, 147,
	62, 147,
	68, 147,
	-2, 102,
	-1, 63,
	2, 148,
	16, 148,
	62, 148,
	68, 148,
	-2, 107,
	-1, 64,
	2, 149,
	16, 149,
	62, 149,
	68, 149,
	-2, 109,
	-1, 65,
	2, 150,
	16, 150,
	62, 150,
	68, 150,
	-2, 111,
	-1, 66,
	2, 151,
	16, 151,
	62, 151,
	68, 151,
	-2, 112,
	-1, 67,
	2, 152,
	16, 152,
	62, 152,
	68, 152,
	-2, 113,
	-1, 68,
	2, 153,
	16, 153,
	62, 153,
	68, 153,
	-2, 114,
	-1, 69,
	2, 154,
	16, 154,
	62, 154,
	68, 154,
	-2, 115,
	-1, 188,
	13, 198,
	14, 198,
	17, 198,
	18, 198,
	24, 198,
	27, 198,
	33, 198,
	34, 198,
	37, 198,
	43, 198,
	47, 198,
	48, 198,
	49, 198,
	50, 198,
	51, 198,
	52, 198,
	53, 198,
	54, 198,
	55, 198,
	56, 198,
	57, 198,
	58, 198,
	62, 198,
	66, 198,
	68, 198,
	71, 198,
	72, 198,
	-2, 0,
	-1, 189,
	13, 198,
	14, 198,
	17, 198,
	18, 198,
	24, 198,
	27, 198,
	33, 198,
	34, 198,
	37, 198,
	43, 198,
	47, 198,
	48, 198,
	49, 198,
	50, 198,
	51, 198,
	52, 198,
	53, 198,
	54, 198,
	55, 198,
	56, 198,
	57, 198,
	58, 198,
	62, 198,
	66, 198,
	68, 198,
	71, 198,
	72, 198,
	-2, 0,
	-1, 209,
	20, 196,
	-2, 0,
	-1, 259,
	20, 197,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 671

var yyAct = [...]int{
	267, 214, 37, 140, 258, 255, 254, 148, 112, 77,
	101, 100, 146, 103, 186, 125, 187, 6, 102, 104,
	188, 189, 250, 57, 152, 147, 270, 249, 151, 120,
	51, 72, 105, 53, 22, 52, 244, 152, 163, 180,
	153, 54, 257, 273, 70, 271, 72, 182, 268, 243,
	18, 19, 151, 153, 20, 151, 107, 205, 108, 105,
	71, 152, 106, 121, 58, 59, 60, 61, 62, 63,
	64, 65, 66, 67, 68, 69, 248, 153, 103, 13,
	109, 149, 150, 24, 104, 30, 142, 160, 31, 32,
	2, 3, 4, 5, 143, 178, 265, 33, 247, 260,
	211, 159, 264, 154, 209, 210, 168, 143, 164, 158,
	161, 156, 167, 157, 155, 263, 7, 177, 208, 143,
	272, 8, 143, 166, 185, 35, 176, 141, 184, 190,
	191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
	201, 202, 203, 99, 81, 204, 183, 126, 127, 128,
	129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
	139, 99, 48, 117, 114, 119, 79, 118, 73, 116,
	95, 170, 98, 171, 83, 113, 246, 78, 206, 207,
	115, 245, 34, 175, 92, 93, 1, 47, 95, 251,
	98, 46, 252, 253, 97, 36, 256, 51, 72, 173,
	53, 22, 52, 56, 45, 114, 9, 9, 54, 172,
	174, 70, 97, 259, 262, 261, 113, 18, 19, 10,
	44, 20, 111, 124, 43, 42, 41, 71, 122, 74,
	162, 58, 59, 60, 61, 62, 63, 64, 65, 66,
	67, 68, 69, 216, 40, 123, 13, 266, 79, 39,
	24, 269, 30, 38, 226, 31, 32, 49, 232, 78,
	144, 181, 274, 80, 179, 76, 275, 212, 75, 145,
	55, 276, 215, 169, 228, 229, 50, 110, 230, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 217, 219,
	221, 222, 223, 231, 233, 236, 237, 238, 239, 240,
	0, 0, 218, 220, 224, 225, 227, 234, 235, 0,
	0, 0, 241, 242, 51, 72, 0, 53, 22, 52,
	0, 0, 0, 0, 0, 54, 0, 0, 70, 0,
	0, 0, 0, 0, 18, 19, 0, 0, 20, 0,
	0, 0, 0, 0, 71, 0, 0, 0, 58, 59,
	60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
	216, 0, 0, 13, 0, 0, 0, 24, 0, 30,
	0, 226, 31, 32, 0, 232, 0, 0, 0, 213,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 228, 229, 0, 0, 230, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 217, 219, 221, 222, 223,
	231, 233, 236, 237, 238, 239, 240, 0, 0, 218,
	220, 224, 225, 227, 234, 235, 0, 17, 72, 241,
	242, 22, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 18, 19, 0,
	0, 20, 0, 17, 33, 0, 0, 22, 0, 0,
	0, 11, 12, 14, 15, 16, 21, 23, 25, 26,
	27, 28, 29, 18, 19, 0, 13, 20, 0, 0,
	24, 0, 30, 0, 0, 31, 32, 11, 12, 14,
	15, 16, 21, 23, 25, 26, 27, 28, 29, 0,
	0, 99, 13, 0, 0, 0, 24, 165, 30, 0,
	0, 31, 32, 82, 83, 84, 0, 85, 86, 87,
	88, 89, 90, 91, 92, 93, 94, 0, 95, 96,
	98, 0, 0, 0, 0, 0, 0, 99, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 82,
	83, 84, 97, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 0, 95, 96, 98, 0, 0, 99,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 82, 83, 84, 0, 85, 86, 87, 97, 89,
	90, 91, 92, 93, 94, 0, 95, 96, 98, 0,
	0, 99, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 82, 83, 84, 0, 85, 86, 99,
	97, 89, 90, 0, 92, 93, 94, 0, 95, 96,
	98, 82, 83, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 92, 93, 0, 0, 95, 96, 98, 0,
	0, 0, 97, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	97,
}

var yyPact = [...]int{
	15, 105, 440, 440, 184, 414, -1000, -1000, -1000, 83,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 246, -1000, 142, -1000, 522, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	16, 43, -1000, 301, -1000, 301, 32, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 203, -1000, -1000, 161, -1000, -1000, 163, -1000,
	6, -1000, -46, -46, -46, -46, -46, -46, -46, -46,
	-46, -46, -46, -46, -46, -46, -46, 84, 10, 112,
	43, -49, -1000, 85, 85, 17, -1000, 486, 128, -1000,
	104, -1000, -1000, 169, -1000, -1000, 164, -1000, 93, -1000,
	34, 301, -1000, -51, -43, -1000, 301, 301, 301, 301,
	301, 301, 301, 301, 301, 301, 301, 301, 301, 301,
	-1000, 109, -1000, -1000, -1000, 41, -1000, -1000, -1000, -1000,
	-1000, -1000, 37, 37, 98, -1000, -1000, -1000, -1000, 358,
	-1000, -1000, 28, -1000, 522, -1000, -1000, 162, -1000, 74,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	2, -3, -1000, -1000, -1000, 146, 85, 85, 85, 85,
	128, 604, 604, 604, 586, 554, 604, 604, 586, 128,
	128, 604, 128, 146, -1000, 21, -1000, -1000, -1000, 97,
	109, -1000, 94, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 301, -1000, -1000, -1000, -1000, 30,
	30, 1, -1000, -1000, -1000, -1000, -1000, -1000, 25, 118,
	-1000, 23, -1000, -1000, 241, -1000, 522, -1000, -1000, -1000,
	30, -1000, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 277, 8, 276, 1, 273, 272, 203, 270, 269,
	219, 268, 121, 9, 267, 5, 6, 264, 263, 0,
	25, 261, 7, 260, 257, 253, 11, 63, 249, 245,
	2, 244, 230, 10, 228, 23, 226, 225, 224, 223,
	220, 204, 191, 187, 162, 3, 4, 186, 182,
}

var yyR1 = [...]int{
	0, 47, 47, 47, 47, 47, 47, 47, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	25, 25, 25, 25, 26, 26, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 27, 29, 29, 39, 39, 34, 34, 34, 34,
	15, 15, 15, 15, 14, 14, 14, 4, 4, 31,
	33, 33, 32, 32, 32, 40, 38, 38, 38, 24,
	24, 24, 9, 9, 36, 42, 42, 42, 42, 42,
	42, 43, 44, 44, 44, 35, 35, 35, 1, 1,
	1, 2, 2, 2, 2, 12, 12, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 10,
	10, 10, 10, 11, 11, 11, 13, 13, 13, 13,
	48, 18, 18, 18, 18, 17, 17, 17, 17, 17,
	21, 21, 21, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 8, 8, 5, 5, 5, 5, 37, 20, 22,
	22, 23, 23, 19, 45, 41, 46, 46, 16, 16,
}

var yyR2 = [...]int{
	0, 2, 2, 2, 2, 2, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 1, 0, 1, 3, 3, 1, 1, 3, 3,
	3, 4, 2, 1, 3, 1, 2, 1, 1, 2,
	3, 2, 3, 1, 2, 3, 3, 4, 3, 3,
	5, 3, 1, 1, 4, 6, 6, 6, 5, 4,
	3, 2, 2, 1, 1, 3, 4, 2, 3, 1,
	2, 3, 3, 2, 1, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	4, 2, 0, 3, 1, 2, 3, 3, 2, 1,
	2, 0, 3, 2, 1, 1, 3, 1, 3, 4,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 1, 1, 1, 1, 1, 0, 1, 0, 1,
}

var yyChk = [...]int{
	-1000, -47, 75, 76, 77, 78, 2, 11, -12, -7,
	-10, 47, 48, 62, 49, 50, 51, 13, 33, 34,
	37, 52, 17, 53, 66, 54, 55, 56, 57, 58,
	68, 71, 72, 14, -48, -12, 11, -30, -25, -28,
	-31, -36, -37, -38, -40, -41, -42, -43, -44, -24,
	-3, 13, 18, 16, 24, -8, -7, -35, 47, 48,
	49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
	27, 43, 14, -44, -10, -11, 19, -13, 13, 2,
	-18, 2, 27, 28, 29, 31, 32, 33, 34, 35,
	36, 37, 38, 39, 40, 42, 43, 66, 44, 15,
	-26, -33, 2, 62, 68, 16, -33, -30, -30, -35,
	-1, 19, -2, 13, 2, 19, 8, 2, 4, 2,
	23, -27, -34, -29, -39, 61, -27, -27, -27, -27,
	-27, -27, -27, -27, -27, -27, -27, -27, -27, -27,
	-45, 43, 2, 10, -23, -9, 2, -20, -22, 71,
	72, 18, 27, 43, -45, 2, -33, -26, -15, 16,
	2, -15, -32, 21, -30, 21, 19, 8, 2, -5,
	2, 4, 40, 30, 41, 19, -13, 24, 2, -17,
	5, -21, 13, -20, -22, -30, 65, 67, 63, 64,
	-30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
	-30, -30, -30, -30, -45, 16, -20, -20, 20, 6,
	7, 2, -14, 21, -4, -6, 2, 47, 61, 48,
	62, 49, 50, 51, 63, 64, 13, 65, 33, 34,
	37, 52, 17, 53, 66, 67, 54, 55, 56, 57,
	58, 71, 72, 21, 8, 19, -2, 24, 2, 25,
	25, -22, -15, -15, -16, -15, -16, 21, -46, -45,
	2, -46, -45, 21, 8, 2, -30, -19, 18, -19,
	25, 20, 2, 20, 21, -4, -19,
}

var yyDef = [...]int{
	0, -2, 122, 122, 0, 0, 7, 6, 1, 122,
	96, 97, 98, 99, 100, 101, 102, 103, 104, 105,
	106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
	116, 117, 118, 0, 2, -2, 3, 4, 8, 9,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	0, 103, 187, 0, 195, 0, 83, 84, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	181, 182, 0, 5, 95, 0, 121, 124, 0, 129,
	130, 134, 42, 42, 42, 42, 42, 42, 42, 42,
	42, 42, 42, 42, 42, 42, 42, 0, 0, 0,
	0, 22, 23, 0, 0, 0, 59, 0, 81, 82,
	0, 87, 89, 0, 94, 119, 0, 125, 0, 128,
	133, 0, 41, 46, 47, 43, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	66, 0, 68, 194, 69, 0, 71, 191, 192, 72,
	73, 188, 0, 0, 0, 80, 20, 21, 24, 0,
	53, 25, 0, 61, 63, 65, 85, 0, 90, 0,
	93, 183, 184, 185, 186, 120, 123, 126, 127, 132,
	135, 137, 140, 141, 142, 26, 0, 0, -2, -2,
	27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 38, 39, 40, 67, 0, 189, 190, 74, -2,
	196, 79, 0, 52, 55, 57, 58, 155, 156, 157,
	158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
	168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
	178, 179, 180, 60, 64, 86, 88, 91, 92, 0,
	0, 0, 44, 45, 48, 199, 49, 70, 0, -2,
	78, 0, 197, 50, 0, 56, 62, 136, 193, 138,
	0, 75, 77, 76, 51, 54, 139,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:174
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].labels
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:177
		{
			yylex.(*parser).addParseErrf(PositionRange{}, "no expression found in input")
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:179
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:181
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:184
		{
			yylex.(*parser).unexpected("", "")
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:207
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[2].node, yyDollar[3].node)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:209
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[2].node)
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:211
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, yyDollar[2].node)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:213
		{
			yylex.(*parser).unexpected("aggregation", "")
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, Expressions{})
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:221
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
			}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:227
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
				Without:  true,
			}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:240
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:241
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:242
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:243
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:244
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:245
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:246
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:247
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:248
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:249
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:250
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:251
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:252
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:253
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:254
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:262
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
			}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:267
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
				ReturnBool:     true,
			}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:275
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:280
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
			yyVAL.node.(*BinaryExpr).VectorMatching.On = true
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:290
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardManyToOne
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:296
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardOneToMany
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:305
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:307
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:309
		{
			yyVAL.strings = []string{}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:311
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.strings = nil
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:317
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].item.Val)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:319
		{
			yyVAL.strings = []string{yyDollar[1].item.Val}
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:321
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.strings = yyDollar[1].strings
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:325
		{
			if !isLabel(yyDollar[1].item.Val) {
				yylex.(*parser).unexpected("grouping opts", "label")
			}
			yyVAL.item = yyDollar[1].item
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:332
		{
			yylex.(*parser).unexpected("grouping opts", "label")
			yyVAL.item = Item{}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:340
		{
			fn, exist := getFunction(yyDollar[1].item.Val)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: PositionRange{
					Start: yyDollar[1].item.Pos,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:357
		{
			yyVAL.node = yyDollar[2].node
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:359
		{
			yyVAL.node = Expressions{}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:363
		{
			yyVAL.node = append(yyDollar[1].node.(Expressions), yyDollar[3].node.(Expr))
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:365
		{
			yyVAL.node = Expressions{yyDollar[1].node.(Expr)}
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:367
		{
			yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "trailing commas not allowed in function call args")
			yyVAL.node = yyDollar[1].node
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:378
		{
			yyVAL.node = &ParenExpr{Expr: yyDollar[2].node.(Expr), PosRange: mergeRanges(&yyDollar[1].item, &yyDollar[3].item)}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:386
		{
			yylex.(*parser).addOffset(yyDollar[1].node, yyDollar[3].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:391
		{
			yylex.(*parser).addOffset(yyDollar[1].node, -yyDollar[4].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:396
		{
			yylex.(*parser).unexpected("offset", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:403
		{
			yylex.(*parser).setTimestamp(yyDollar[1].node, yyDollar[3].float)
			yyVAL.node = yyDollar[1].node
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
//line generated_parser.y:408
		{
			yylex.(*parser).setAtModifierPreprocessor(yyDollar[1].node, yyDollar[3].item)
			yyVAL.node = yyDollar[1].node
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:413
		{
			yylex.(*parser).unexpected("@", "timestamp")
			yyVAL.node = yyDollar[1].node
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:423
		{
			var errMsg string
			vs, ok := yyDollar[1].node.(*VectorSelector)
			if !ok {
				errMsg = "ranges only allowed for vector selectors"
			} else if vs.OriginalOffset != 0 {
				errMsg = "no offset modifiers allowed before range"
			} else if vs.Timestamp != nil {
				errMsg = "no @ modifiers allowed before range"
			}

			if errMsg != "" {
				errRange := mergeRanges(&yyDollar[2].item, &yyDollar[4].item)
				yylex.(*parser).addParseErrf(errRange, errMsg)
			}

			yyVAL.node = &MatrixSelector{
				VectorSelector: yyDollar[1].node.(Expr),
				Range:          yyDollar[3].duration,
				EndPos:         yylex.(*parser).lastClosing,
			}
		}
	case 75:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:448
		{
			yyVAL.node = &SubqueryExpr{
				Expr:  yyDollar[1].node.(Expr),
				Range: yyDollar[3].duration,
				Step:  yyDollar[5].duration,

				EndPos: yyDollar[6].item.Pos + 1,
			}
		}
	case 76:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:458
		{
			yyVAL.node = &SubqueryExpr{
				Expr:          yyDollar[1].node.(Expr),
				Range:         yyDollar[3].duration,
				Step:          yyDollar[5].duration,
				AlignEvalTime: true,
				EndPos:        yyDollar[6].item.Pos + 1,
			}
		}
	case 77:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:468
		{
			yylex.(*parser).unexpected("subquery selector", "\"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 78:
		yyDollar = yyS[yypt-5 : yypt+1]
//line generated_parser.y:470
		{
			yylex.(*parser).unexpected("subquery selector", "duration or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 79:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:472
		{
			yylex.(*parser).unexpected("subquery or range", "\":\" or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:474
		{
			yylex.(*parser).unexpected("subquery selector", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:484
		{
			if nl, ok := yyDollar[2].node.(*NumberLiteral); ok {
				if yyDollar[1].item.Typ == SUB {
					nl.Val *= -1
				}
				nl.PosRange.Start = yyDollar[1].item.Pos
				yyVAL.node = nl
			} else {
				yyVAL.node = &UnaryExpr{Op: yyDollar[1].item.Typ, Expr: yyDollar[2].node.(Expr), StartPos: yyDollar[1].item.Pos}
			}
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:502
		{
			vs := yyDollar[2].node.(*VectorSelector)
			vs.PosRange = mergeRanges(&yyDollar[1].item, vs)
			vs.Name = yyDollar[1].item.Val
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:510
		{
			vs := &VectorSelector{
				Name:          yyDollar[1].item.Val,
				LabelMatchers: []*labels.Matcher{},
				PosRange:      yyDollar[1].item.PositionRange(),
			}
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:520
		{
			vs := yyDollar[1].node.(*VectorSelector)
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:528
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[3].item),
			}
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:535
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[4].item),
			}
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:542
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: []*labels.Matcher{},
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[2].item),
			}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:551
		{
			if yyDollar[1].matchers != nil {
				yyVAL.matchers = append(yyDollar[1].matchers, yyDollar[3].matcher)
			} else {
				yyVAL.matchers = yyDollar[1].matchers
			}
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:559
		{
			yyVAL.matchers = []*labels.Matcher{yyDollar[1].matcher}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:561
		{
			yylex.(*parser).unexpected("label matching", "\",\" or \"}\"")
			yyVAL.matchers = yyDollar[1].matchers
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:565
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:567
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:569
		{
			yylex.(*parser).unexpected("label matching", "label matching operator")
			yyVAL.matcher = nil
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:571
		{
			yylex.(*parser).unexpected("label matching", "identifier or \"}\"")
			yyVAL.matcher = nil
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:579
		{
			yyVAL.labels = append(yyDollar[2].labels, labels.Label{Name: labels.MetricName, Value: yyDollar[1].item.Val})
			sort.Sort(yyVAL.labels)
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:581
		{
			yyVAL.labels = yyDollar[1].labels
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:588
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 120:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:590
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 121:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:592
		{
			yyVAL.labels = labels.New()
		}
	case 122:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:594
		{
			yyVAL.labels = labels.New()
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:598
		{
			yyVAL.labels = append(yyDollar[1].labels, yyDollar[3].label)
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:600
		{
			yyVAL.labels = []labels.Label{yyDollar[1].label}
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:602
		{
			yylex.(*parser).unexpected("label set", "\",\" or \"}\"")
			yyVAL.labels = yyDollar[1].labels
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:607
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:609
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:611
		{
			yylex.(*parser).unexpected("label set", "\"=\"")
			yyVAL.label = labels.Label{}
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:613
		{
			yylex.(*parser).unexpected("label set", "identifier or \"}\"")
			yyVAL.label = labels.Label{}
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:621
		{
			yylex.(*parser).generatedParserResult = &seriesDescription{
				labels: yyDollar[1].labels,
				values: yyDollar[2].series,
			}
		}
	case 131:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:630
		{
			yyVAL.series = []SequenceValue{}
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:632
		{
			yyVAL.series = append(yyDollar[1].series, yyDollar[3].series...)
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:634
		{
			yyVAL.series = yyDollar[1].series
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:636
		{
			yylex.(*parser).unexpected("series values", "")
			yyVAL.series = nil
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:640
		{
			yyVAL.series = []SequenceValue{{Omitted: true}}
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:642
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i < yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Omitted: true})
			}
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:649
		{
			yyVAL.series = []SequenceValue{{Value: yyDollar[1].float}}
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:651
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
			}
		}
	case 139:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:658
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[4].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
				yyDollar[1].float += yyDollar[2].float
			}
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:668
		{
			if yyDollar[1].item.Val != "stale" {
				yylex.(*parser).unexpected("series values", "number or \"stale\"")
			}
			yyVAL.float = math.Float64frombits(value.StaleNaN)
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:699
		{
			yyVAL.node = &NumberLiteral{
				Val:      yylex.(*parser).number(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:707
		{
			yyVAL.float = yylex.(*parser).number(yyDollar[1].item.Val)
		}
	case 189:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:709
		{
			yyVAL.float = yyDollar[2].float
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:710
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:716
		{
			var err error
			yyVAL.uint, err = strconv.ParseUint(yyDollar[1].item.Val, 10, 64)
			if err != nil {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid repetition in series values: %s", err)
			}
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:726
		{
			var err error
			yyVAL.duration, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:737
		{
			yyVAL.node = &StringLiteral{
				Val:      yylex.(*parser).unquoteString(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 196:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:750
		{
			yyVAL.duration = 0
		}
	case 198:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:754
		{
			yyVAL.strings = nil
		}
	}
	goto yystack /* stack new state and value */
}
