// Code generated by goyacc -o generated_parser.y.go generated_parser.y. DO NOT EDIT.

//line generated_parser.y:15
package parser

import __yyfmt__ "fmt"

//line generated_parser.y:15

import (
	"math"
	"sort"
	"strconv"
	"time"

	"github.com/prometheus/prometheus/pkg/labels"
	"github.com/prometheus/prometheus/pkg/value"
)

//line generated_parser.y:28
type yySymType struct {
	yys      int
	node     Node
	item     Item
	matchers []*labels.Matcher
	matcher  *labels.Matcher
	label    labels.Label
	labels   labels.Labels
	strings  []string
	series   []SequenceValue
	uint     uint64
	float    float64
	duration time.Duration
}

const EQL = 57346
const BLANK = 57347
const COLON = 57348
const COMMA = 57349
const COMMENT = 57350
const DURATION = 57351
const EOF = 57352
const ERROR = 57353
const IDENTIFIER = 57354
const LEFT_BRACE = 57355
const LEFT_BRACKET = 57356
const LEFT_PAREN = 57357
const METRIC_IDENTIFIER = 57358
const NUMBER = 57359
const RIGHT_BRACE = 57360
const RIGHT_BRACKET = 57361
const RIGHT_PAREN = 57362
const SEMICOLON = 57363
const SPACE = 57364
const STRING = 57365
const TIMES = 57366
const operatorsStart = 57367
const ADD = 57368
const DIV = 57369
const EQLC = 57370
const EQL_REGEX = 57371
const GTE = 57372
const GTR = 57373
const LAND = 57374
const LOR = 57375
const LSS = 57376
const LTE = 57377
const LUNLESS = 57378
const MOD = 57379
const MUL = 57380
const NEQ = 57381
const NEQ_REGEX = 57382
const POW = 57383
const SUB = 57384
const AT = 57385
const operatorsEnd = 57386
const aggregatorsStart = 57387
const AVG = 57388
const BOTTOMK = 57389
const COUNT = 57390
const COUNT_VALUES = 57391
const GROUP = 57392
const MAX = 57393
const MIN = 57394
const QUANTILE = 57395
const STDDEV = 57396
const STDVAR = 57397
const SUM = 57398
const TOPK = 57399
const aggregatorsEnd = 57400
const keywordsStart = 57401
const BOOL = 57402
const BY = 57403
const GROUP_LEFT = 57404
const GROUP_RIGHT = 57405
const IGNORING = 57406
const OFFSET = 57407
const ON = 57408
const WITHOUT = 57409
const keywordsEnd = 57410
const preprocessorStart = 57411
const START = 57412
const END = 57413
const preprocessorEnd = 57414
const startSymbolsStart = 57415
const START_METRIC = 57416
const START_SERIES_DESCRIPTION = 57417
const START_EXPRESSION = 57418
const START_METRIC_SELECTOR = 57419
const startSymbolsEnd = 57420

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"EQL",
	"BLANK",
	"COLON",
	"COMMA",
	"COMMENT",
	"DURATION",
	"EOF",
	"ERROR",
	"IDENTIFIER",
	"LEFT_BRACE",
	"LEFT_BRACKET",
	"LEFT_PAREN",
	"METRIC_IDENTIFIER",
	"NUMBER",
	"RIGHT_BRACE",
	"RIGHT_BRACKET",
	"RIGHT_PAREN",
	"SEMICOLON",
	"SPACE",
	"STRING",
	"TIMES",
	"operatorsStart",
	"ADD",
	"DIV",
	"EQLC",
	"EQL_REGEX",
	"GTE",
	"GTR",
	"LAND",
	"LOR",
	"LSS",
	"LTE",
	"LUNLESS",
	"MOD",
	"MUL",
	"NEQ",
	"NEQ_REGEX",
	"POW",
	"SUB",
	"AT",
	"operatorsEnd",
	"aggregatorsStart",
	"AVG",
	"BOTTOMK",
	"COUNT",
	"COUNT_VALUES",
	"GROUP",
	"MAX",
	"MIN",
	"QUANTILE",
	"STDDEV",
	"STDVAR",
	"SUM",
	"TOPK",
	"aggregatorsEnd",
	"keywordsStart",
	"BOOL",
	"BY",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"IGNORING",
	"OFFSET",
	"ON",
	"WITHOUT",
	"keywordsEnd",
	"preprocessorStart",
	"START",
	"END",
	"preprocessorEnd",
	"startSymbolsStart",
	"START_METRIC",
	"START_SERIES_DESCRIPTION",
	"START_EXPRESSION",
	"START_METRIC_SELECTOR",
	"startSymbolsEnd",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line generated_parser.y:757

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 35,
	1, 131,
	10, 131,
	22, 131,
	-2, 0,
	-1, 58,
	2, 143,
	15, 143,
	61, 143,
	67, 143,
	-2, 97,
	-1, 59,
	2, 144,
	15, 144,
	61, 144,
	67, 144,
	-2, 98,
	-1, 60,
	2, 145,
	15, 145,
	61, 145,
	67, 145,
	-2, 100,
	-1, 61,
	2, 146,
	15, 146,
	61, 146,
	67, 146,
	-2, 101,
	-1, 62,
	2, 147,
	15, 147,
	61, 147,
	67, 147,
	-2, 102,
	-1, 63,
	2, 148,
	15, 148,
	61, 148,
	67, 148,
	-2, 107,
	-1, 64,
	2, 149,
	15, 149,
	61, 149,
	67, 149,
	-2, 109,
	-1, 65,
	2, 150,
	15, 150,
	61, 150,
	67, 150,
	-2, 111,
	-1, 66,
	2, 151,
	15, 151,
	61, 151,
	67, 151,
	-2, 112,
	-1, 67,
	2, 152,
	15, 152,
	61, 152,
	67, 152,
	-2, 113,
	-1, 68,
	2, 153,
	15, 153,
	61, 153,
	67, 153,
	-2, 114,
	-1, 69,
	2, 154,
	15, 154,
	61, 154,
	67, 154,
	-2, 115,
	-1, 188,
	12, 198,
	13, 198,
	16, 198,
	17, 198,
	23, 198,
	26, 198,
	32, 198,
	33, 198,
	36, 198,
	42, 198,
	46, 198,
	47, 198,
	48, 198,
	49, 198,
	50, 198,
	51, 198,
	52, 198,
	53, 198,
	54, 198,
	55, 198,
	56, 198,
	57, 198,
	61, 198,
	65, 198,
	67, 198,
	70, 198,
	71, 198,
	-2, 0,
	-1, 189,
	12, 198,
	13, 198,
	16, 198,
	17, 198,
	23, 198,
	26, 198,
	32, 198,
	33, 198,
	36, 198,
	42, 198,
	46, 198,
	47, 198,
	48, 198,
	49, 198,
	50, 198,
	51, 198,
	52, 198,
	53, 198,
	54, 198,
	55, 198,
	56, 198,
	57, 198,
	61, 198,
	65, 198,
	67, 198,
	70, 198,
	71, 198,
	-2, 0,
	-1, 209,
	19, 196,
	-2, 0,
	-1, 259,
	19, 197,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 667

var yyAct = [...]int{
	265, 213, 140, 37, 257, 253, 254, 148, 112, 77,
	103, 101, 100, 146, 125, 186, 104, 187, 6, 102,
	188, 189, 268, 248, 147, 249, 120, 152, 151, 99,
	51, 72, 105, 53, 22, 52, 243, 152, 163, 57,
	180, 54, 256, 153, 70, 276, 269, 182, 266, 242,
	18, 19, 151, 153, 20, 247, 95, 107, 98, 108,
	71, 152, 121, 106, 58, 59, 60, 61, 62, 63,
	64, 65, 66, 67, 68, 69, 246, 153, 103, 13,
	97, 149, 150, 24, 104, 30, 178, 142, 31, 32,
	2, 3, 4, 5, 143, 263, 109, 151, 205, 210,
	262, 168, 154, 209, 105, 114, 167, 177, 79, 164,
	158, 161, 156, 261, 157, 113, 208, 166, 78, 10,
	72, 244, 33, 7, 175, 185, 176, 141, 184, 74,
	190, 191, 192, 193, 194, 195, 196, 197, 198, 199,
	200, 201, 202, 203, 204, 183, 126, 127, 128, 129,
	130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
	160, 143, 260, 117, 114, 79, 258, 8, 116, 143,
	119, 35, 118, 159, 113, 78, 245, 206, 207, 115,
	111, 76, 272, 81, 34, 36, 99, 51, 72, 250,
	53, 22, 52, 251, 252, 255, 155, 1, 54, 83,
	48, 70, 47, 143, 46, 45, 73, 18, 19, 92,
	93, 20, 259, 95, 44, 98, 170, 71, 171, 124,
	43, 58, 59, 60, 61, 62, 63, 64, 65, 66,
	67, 68, 69, 42, 41, 56, 13, 97, 9, 9,
	24, 215, 30, 173, 122, 31, 32, 264, 162, 40,
	267, 225, 123, 172, 174, 231, 39, 38, 49, 273,
	144, 271, 181, 270, 274, 80, 179, 211, 75, 275,
	145, 227, 228, 55, 214, 229, 169, 50, 110, 0,
	0, 0, 0, 0, 0, 216, 218, 220, 221, 222,
	230, 232, 235, 236, 237, 238, 239, 0, 0, 217,
	219, 223, 224, 226, 233, 234, 0, 0, 0, 240,
	241, 51, 72, 0, 53, 22, 52, 0, 0, 0,
	0, 0, 54, 0, 0, 70, 0, 0, 0, 0,
	0, 18, 19, 0, 0, 20, 0, 0, 0, 0,
	0, 71, 0, 0, 0, 58, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 215, 0, 0,
	13, 0, 0, 0, 24, 0, 30, 225, 0, 31,
	32, 231, 0, 0, 0, 212, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 227, 228, 0,
	0, 229, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 216, 218, 220, 221, 222, 230, 232, 235, 236,
	237, 238, 239, 0, 0, 217, 219, 223, 224, 226,
	233, 234, 0, 17, 72, 240, 241, 22, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 18, 19, 0, 0, 20, 0, 17,
	33, 0, 0, 22, 0, 0, 0, 11, 12, 14,
	15, 16, 21, 23, 25, 26, 27, 28, 29, 18,
	19, 0, 13, 20, 0, 0, 24, 0, 30, 0,
	0, 31, 32, 11, 12, 14, 15, 16, 21, 23,
	25, 26, 27, 28, 29, 0, 0, 99, 13, 0,
	0, 0, 24, 165, 30, 0, 0, 31, 32, 82,
	83, 84, 0, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 0, 95, 96, 98, 0, 0, 0,
	0, 0, 0, 99, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 82, 83, 84, 97, 85,
	86, 87, 88, 89, 90, 91, 92, 93, 94, 0,
	95, 96, 98, 0, 0, 99, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 82, 83, 84,
	0, 85, 86, 87, 97, 89, 90, 91, 92, 93,
	94, 0, 95, 96, 98, 0, 0, 99, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 82,
	83, 84, 0, 85, 86, 99, 97, 89, 90, 0,
	92, 93, 94, 0, 95, 96, 98, 82, 83, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 92, 93,
	0, 0, 95, 96, 98, 0, 0, 0, 97, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 97,
}

var yyPact = [...]int{
	16, 113, 437, 437, 175, 411, -1000, -1000, -1000, 109,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 163, -1000, 181, -1000, 519, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	17, 89, -1000, 299, -1000, 299, 107, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 162, -1000, -1000, 161, -1000, -1000, 168, -1000,
	4, -1000, -46, -46, -46, -46, -46, -46, -46, -46,
	-46, -46, -46, -46, -46, -46, -46, 85, 11, 194,
	89, -51, -1000, 158, 158, 18, -1000, 483, 15, -1000,
	99, -1000, -1000, 214, -1000, -1000, 106, -1000, 84, -1000,
	35, 299, -1000, -49, -42, -1000, 299, 299, 299, 299,
	299, 299, 299, 299, 299, 299, 299, 299, 299, 299,
	-1000, 152, -1000, -1000, -1000, 83, -1000, -1000, -1000, -1000,
	-1000, -1000, 80, 80, 97, -1000, -1000, -1000, -1000, 355,
	-1000, -1000, 29, -1000, 519, -1000, -1000, 103, -1000, 53,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1, 1, -1000, -1000, -1000, 172, 158, 158, 158, 158,
	15, 601, 601, 601, 583, 551, 601, 601, 583, 15,
	15, 601, 15, 172, -1000, 22, -1000, -1000, -1000, 160,
	-1000, 93, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 299, -1000, -1000, -1000, -1000, 31, 31,
	-2, -1000, -1000, -1000, -1000, -1000, -1000, 27, 152, 180,
	-1000, -1000, 239, -1000, 519, -1000, -1000, -1000, 31, -1000,
	26, -1000, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 278, 8, 277, 1, 276, 274, 235, 273, 270,
	119, 268, 167, 9, 267, 6, 5, 266, 265, 0,
	24, 262, 7, 260, 258, 257, 12, 62, 256, 252,
	3, 249, 248, 11, 244, 39, 234, 233, 220, 219,
	214, 205, 204, 202, 200, 2, 4, 197, 184,
}

var yyR1 = [...]int{
	0, 47, 47, 47, 47, 47, 47, 47, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	25, 25, 25, 25, 26, 26, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 27, 29, 29, 39, 39, 34, 34, 34, 34,
	15, 15, 15, 15, 14, 14, 14, 4, 4, 31,
	33, 33, 32, 32, 32, 40, 38, 38, 38, 24,
	24, 24, 9, 9, 36, 42, 42, 42, 42, 42,
	42, 43, 44, 44, 44, 35, 35, 35, 1, 1,
	1, 2, 2, 2, 2, 12, 12, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 10,
	10, 10, 10, 11, 11, 11, 13, 13, 13, 13,
	48, 18, 18, 18, 18, 17, 17, 17, 17, 17,
	21, 21, 21, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 8, 8, 5, 5, 5, 5, 37, 20, 22,
	22, 23, 23, 19, 45, 41, 46, 46, 16, 16,
}

var yyR2 = [...]int{
	0, 2, 2, 2, 2, 2, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 1, 0, 1, 3, 3, 1, 1, 3, 3,
	3, 4, 2, 1, 3, 1, 2, 1, 1, 2,
	3, 2, 3, 1, 2, 3, 3, 4, 3, 3,
	5, 3, 1, 1, 4, 6, 7, 6, 5, 4,
	3, 2, 2, 1, 1, 3, 4, 2, 3, 1,
	2, 3, 3, 2, 1, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	4, 2, 0, 3, 1, 2, 3, 3, 2, 1,
	2, 0, 3, 2, 1, 1, 3, 1, 3, 4,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
	2, 1, 1, 1, 1, 1, 0, 1, 0, 1,
}

var yyChk = [...]int{
	-1000, -47, 74, 75, 76, 77, 2, 10, -12, -7,
	-10, 46, 47, 61, 48, 49, 50, 12, 32, 33,
	36, 51, 16, 52, 65, 53, 54, 55, 56, 57,
	67, 70, 71, 13, -48, -12, 10, -30, -25, -28,
	-31, -36, -37, -38, -40, -41, -42, -43, -44, -24,
	-3, 12, 17, 15, 23, -8, -7, -35, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	26, 42, 13, -44, -10, -11, 18, -13, 12, 2,
	-18, 2, 26, 27, 28, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 41, 42, 65, 43, 14,
	-26, -33, 2, 61, 67, 15, -33, -30, -30, -35,
	-1, 18, -2, 12, 2, 18, 7, 2, 4, 2,
	22, -27, -34, -29, -39, 60, -27, -27, -27, -27,
	-27, -27, -27, -27, -27, -27, -27, -27, -27, -27,
	-45, 42, 2, 9, -23, -9, 2, -20, -22, 70,
	71, 17, 26, 42, -45, 2, -33, -26, -15, 15,
	2, -15, -32, 20, -30, 20, 18, 7, 2, -5,
	2, 4, 39, 29, 40, 18, -13, 23, 2, -17,
	5, -21, 12, -20, -22, -30, 64, 66, 62, 63,
	-30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
	-30, -30, -30, -30, -45, 15, -20, -20, 19, 6,
	2, -14, 20, -4, -6, 2, 46, 60, 47, 61,
	48, 49, 50, 62, 63, 12, 64, 32, 33, 36,
	51, 16, 52, 65, 66, 53, 54, 55, 56, 57,
	70, 71, 20, 7, 18, -2, 23, 2, 24, 24,
	-22, -15, -15, -16, -15, -16, 20, -46, 6, -45,
	2, 20, 7, 2, -30, -19, 17, -19, 24, 19,
	-46, -45, 2, 20, -4, -19, 19,
}

var yyDef = [...]int{
	0, -2, 122, 122, 0, 0, 7, 6, 1, 122,
	96, 97, 98, 99, 100, 101, 102, 103, 104, 105,
	106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
	116, 117, 118, 0, 2, -2, 3, 4, 8, 9,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	0, 103, 187, 0, 195, 0, 83, 84, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	181, 182, 0, 5, 95, 0, 121, 124, 0, 129,
	130, 134, 42, 42, 42, 42, 42, 42, 42, 42,
	42, 42, 42, 42, 42, 42, 42, 0, 0, 0,
	0, 22, 23, 0, 0, 0, 59, 0, 81, 82,
	0, 87, 89, 0, 94, 119, 0, 125, 0, 128,
	133, 0, 41, 46, 47, 43, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	66, 0, 68, 194, 69, 0, 71, 191, 192, 72,
	73, 188, 0, 0, 0, 80, 20, 21, 24, 0,
	53, 25, 0, 61, 63, 65, 85, 0, 90, 0,
	93, 183, 184, 185, 186, 120, 123, 126, 127, 132,
	135, 137, 140, 141, 142, 26, 0, 0, -2, -2,
	27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 38, 39, 40, 67, 0, 189, 190, 74, -2,
	79, 0, 52, 55, 57, 58, 155, 156, 157, 158,
	159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
	169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
	179, 180, 60, 64, 86, 88, 91, 92, 0, 0,
	0, 44, 45, 48, 199, 49, 70, 0, 196, -2,
	78, 50, 0, 56, 62, 136, 193, 138, 0, 75,
	0, 197, 77, 51, 54, 139, 76,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:173
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].labels
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:176
		{
			yylex.(*parser).addParseErrf(PositionRange{}, "no expression found in input")
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:178
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:180
		{
			yylex.(*parser).generatedParserResult = yyDollar[2].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:183
		{
			yylex.(*parser).unexpected("", "")
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:206
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[2].node, yyDollar[3].node)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:208
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, yyDollar[3].node, yyDollar[2].node)
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:210
		{
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, yyDollar[2].node)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:212
		{
			yylex.(*parser).unexpected("aggregation", "")
			yyVAL.node = yylex.(*parser).newAggregateExpr(yyDollar[1].item, &AggregateExpr{}, Expressions{})
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:220
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
			}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:226
		{
			yyVAL.node = &AggregateExpr{
				Grouping: yyDollar[2].strings,
				Without:  true,
			}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:239
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:240
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:241
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:242
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:243
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:244
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:245
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:246
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:247
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:248
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:249
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:250
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:251
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:252
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:253
		{
			yyVAL.node = yylex.(*parser).newBinaryExpression(yyDollar[1].node, yyDollar[2].item, yyDollar[3].node, yyDollar[4].node)
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:261
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
			}
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:266
		{
			yyVAL.node = &BinaryExpr{
				VectorMatching: &VectorMatching{Card: CardOneToOne},
				ReturnBool:     true,
			}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:274
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:279
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.MatchingLabels = yyDollar[3].strings
			yyVAL.node.(*BinaryExpr).VectorMatching.On = true
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:289
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardManyToOne
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:295
		{
			yyVAL.node = yyDollar[1].node
			yyVAL.node.(*BinaryExpr).VectorMatching.Card = CardOneToMany
			yyVAL.node.(*BinaryExpr).VectorMatching.Include = yyDollar[3].strings
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:304
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:306
		{
			yyVAL.strings = yyDollar[2].strings
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:308
		{
			yyVAL.strings = []string{}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:310
		{
			yylex.(*parser).unexpected("grouping opts", "\"(\"")
			yyVAL.strings = nil
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:316
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].item.Val)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:318
		{
			yyVAL.strings = []string{yyDollar[1].item.Val}
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:320
		{
			yylex.(*parser).unexpected("grouping opts", "\",\" or \")\"")
			yyVAL.strings = yyDollar[1].strings
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:324
		{
			if !isLabel(yyDollar[1].item.Val) {
				yylex.(*parser).unexpected("grouping opts", "label")
			}
			yyVAL.item = yyDollar[1].item
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:331
		{
			yylex.(*parser).unexpected("grouping opts", "label")
			yyVAL.item = Item{}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:339
		{
			fn, exist := getFunction(yyDollar[1].item.Val)
			if !exist {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "unknown function with name %q", yyDollar[1].item.Val)
			}
			yyVAL.node = &Call{
				Func: fn,
				Args: yyDollar[2].node.(Expressions),
				PosRange: PositionRange{
					Start: yyDollar[1].item.Pos,
					End:   yylex.(*parser).lastClosing,
				},
			}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:356
		{
			yyVAL.node = yyDollar[2].node
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:358
		{
			yyVAL.node = Expressions{}
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:362
		{
			yyVAL.node = append(yyDollar[1].node.(Expressions), yyDollar[3].node.(Expr))
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:364
		{
			yyVAL.node = Expressions{yyDollar[1].node.(Expr)}
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:366
		{
			yylex.(*parser).addParseErrf(yyDollar[2].item.PositionRange(), "trailing commas not allowed in function call args")
			yyVAL.node = yyDollar[1].node
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:377
		{
			yyVAL.node = &ParenExpr{Expr: yyDollar[2].node.(Expr), PosRange: mergeRanges(&yyDollar[1].item, &yyDollar[3].item)}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:385
		{
			yylex.(*parser).addOffset(yyDollar[1].node, yyDollar[3].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:390
		{
			yylex.(*parser).addOffset(yyDollar[1].node, -yyDollar[4].duration)
			yyVAL.node = yyDollar[1].node
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:395
		{
			yylex.(*parser).unexpected("offset", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:402
		{
			yylex.(*parser).setTimestamp(yyDollar[1].node, yyDollar[3].float)
			yyVAL.node = yyDollar[1].node
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
//line generated_parser.y:407
		{
			yylex.(*parser).setAtModifierPreprocessor(yyDollar[1].node, yyDollar[3].item)
			yyVAL.node = yyDollar[1].node
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:412
		{
			yylex.(*parser).unexpected("@", "timestamp")
			yyVAL.node = yyDollar[1].node
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:422
		{
			var errMsg string
			vs, ok := yyDollar[1].node.(*VectorSelector)
			if !ok {
				errMsg = "ranges only allowed for vector selectors"
			} else if vs.OriginalOffset != 0 {
				errMsg = "no offset modifiers allowed before range"
			} else if vs.Timestamp != nil {
				errMsg = "no @ modifiers allowed before range"
			}

			if errMsg != "" {
				errRange := mergeRanges(&yyDollar[2].item, &yyDollar[4].item)
				yylex.(*parser).addParseErrf(errRange, errMsg)
			}

			yyVAL.node = &MatrixSelector{
				VectorSelector: yyDollar[1].node.(Expr),
				Range:          yyDollar[3].duration,
				EndPos:         yylex.(*parser).lastClosing,
			}
		}
	case 75:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:447
		{
			yyVAL.node = &SubqueryExpr{
				Expr:  yyDollar[1].node.(Expr),
				Range: yyDollar[3].duration,
				Step:  yyDollar[5].duration,

				EndPos: yyDollar[6].item.Pos + 1,
			}
		}
	case 76:
		yyDollar = yyS[yypt-7 : yypt+1]
//line generated_parser.y:457
		{
			yyVAL.node = &SubqueryExpr{
				Expr:          yyDollar[1].node.(Expr),
				Range:         yyDollar[3].duration,
				Step:          yyDollar[6].duration,
				AlignEvalTime: true,
				EndPos:        yyDollar[7].item.Pos + 1,
			}
		}
	case 77:
		yyDollar = yyS[yypt-6 : yypt+1]
//line generated_parser.y:467
		{
			yylex.(*parser).unexpected("subquery selector", "\"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 78:
		yyDollar = yyS[yypt-5 : yypt+1]
//line generated_parser.y:469
		{
			yylex.(*parser).unexpected("subquery selector", "duration or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 79:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:471
		{
			yylex.(*parser).unexpected("subquery or range", "\":\" or \"]\"")
			yyVAL.node = yyDollar[1].node
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:473
		{
			yylex.(*parser).unexpected("subquery selector", "duration")
			yyVAL.node = yyDollar[1].node
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:483
		{
			if nl, ok := yyDollar[2].node.(*NumberLiteral); ok {
				if yyDollar[1].item.Typ == SUB {
					nl.Val *= -1
				}
				nl.PosRange.Start = yyDollar[1].item.Pos
				yyVAL.node = nl
			} else {
				yyVAL.node = &UnaryExpr{Op: yyDollar[1].item.Typ, Expr: yyDollar[2].node.(Expr), StartPos: yyDollar[1].item.Pos}
			}
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:501
		{
			vs := yyDollar[2].node.(*VectorSelector)
			vs.PosRange = mergeRanges(&yyDollar[1].item, vs)
			vs.Name = yyDollar[1].item.Val
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:509
		{
			vs := &VectorSelector{
				Name:          yyDollar[1].item.Val,
				LabelMatchers: []*labels.Matcher{},
				PosRange:      yyDollar[1].item.PositionRange(),
			}
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:519
		{
			vs := yyDollar[1].node.(*VectorSelector)
			yylex.(*parser).assembleVectorSelector(vs)
			yyVAL.node = vs
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:527
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[3].item),
			}
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:534
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: yyDollar[2].matchers,
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[4].item),
			}
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:541
		{
			yyVAL.node = &VectorSelector{
				LabelMatchers: []*labels.Matcher{},
				PosRange:      mergeRanges(&yyDollar[1].item, &yyDollar[2].item),
			}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:550
		{
			if yyDollar[1].matchers != nil {
				yyVAL.matchers = append(yyDollar[1].matchers, yyDollar[3].matcher)
			} else {
				yyVAL.matchers = yyDollar[1].matchers
			}
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:558
		{
			yyVAL.matchers = []*labels.Matcher{yyDollar[1].matcher}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:560
		{
			yylex.(*parser).unexpected("label matching", "\",\" or \"}\"")
			yyVAL.matchers = yyDollar[1].matchers
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:564
		{
			yyVAL.matcher = yylex.(*parser).newLabelMatcher(yyDollar[1].item, yyDollar[2].item, yyDollar[3].item)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:566
		{
			yylex.(*parser).unexpected("label matching", "string")
			yyVAL.matcher = nil
		}
	case 93:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:568
		{
			yylex.(*parser).unexpected("label matching", "label matching operator")
			yyVAL.matcher = nil
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:570
		{
			yylex.(*parser).unexpected("label matching", "identifier or \"}\"")
			yyVAL.matcher = nil
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:578
		{
			yyVAL.labels = append(yyDollar[2].labels, labels.Label{Name: labels.MetricName, Value: yyDollar[1].item.Val})
			sort.Sort(yyVAL.labels)
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:580
		{
			yyVAL.labels = yyDollar[1].labels
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:587
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 120:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:589
		{
			yyVAL.labels = labels.New(yyDollar[2].labels...)
		}
	case 121:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:591
		{
			yyVAL.labels = labels.New()
		}
	case 122:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:593
		{
			yyVAL.labels = labels.New()
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:597
		{
			yyVAL.labels = append(yyDollar[1].labels, yyDollar[3].label)
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:599
		{
			yyVAL.labels = []labels.Label{yyDollar[1].label}
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:601
		{
			yylex.(*parser).unexpected("label set", "\",\" or \"}\"")
			yyVAL.labels = yyDollar[1].labels
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:606
		{
			yyVAL.label = labels.Label{Name: yyDollar[1].item.Val, Value: yylex.(*parser).unquoteString(yyDollar[3].item.Val)}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:608
		{
			yylex.(*parser).unexpected("label set", "string")
			yyVAL.label = labels.Label{}
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:610
		{
			yylex.(*parser).unexpected("label set", "\"=\"")
			yyVAL.label = labels.Label{}
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:612
		{
			yylex.(*parser).unexpected("label set", "identifier or \"}\"")
			yyVAL.label = labels.Label{}
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:620
		{
			yylex.(*parser).generatedParserResult = &seriesDescription{
				labels: yyDollar[1].labels,
				values: yyDollar[2].series,
			}
		}
	case 131:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:629
		{
			yyVAL.series = []SequenceValue{}
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:631
		{
			yyVAL.series = append(yyDollar[1].series, yyDollar[3].series...)
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:633
		{
			yyVAL.series = yyDollar[1].series
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:635
		{
			yylex.(*parser).unexpected("series values", "")
			yyVAL.series = nil
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:639
		{
			yyVAL.series = []SequenceValue{{Omitted: true}}
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:641
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i < yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Omitted: true})
			}
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:648
		{
			yyVAL.series = []SequenceValue{{Value: yyDollar[1].float}}
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line generated_parser.y:650
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[3].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
			}
		}
	case 139:
		yyDollar = yyS[yypt-4 : yypt+1]
//line generated_parser.y:657
		{
			yyVAL.series = []SequenceValue{}
			for i := uint64(0); i <= yyDollar[4].uint; i++ {
				yyVAL.series = append(yyVAL.series, SequenceValue{Value: yyDollar[1].float})
				yyDollar[1].float += yyDollar[2].float
			}
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:667
		{
			if yyDollar[1].item.Val != "stale" {
				yylex.(*parser).unexpected("series values", "number or \"stale\"")
			}
			yyVAL.float = math.Float64frombits(value.StaleNaN)
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:698
		{
			yyVAL.node = &NumberLiteral{
				Val:      yylex.(*parser).number(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:706
		{
			yyVAL.float = yylex.(*parser).number(yyDollar[1].item.Val)
		}
	case 189:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:708
		{
			yyVAL.float = yyDollar[2].float
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
//line generated_parser.y:709
		{
			yyVAL.float = -yyDollar[2].float
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:715
		{
			var err error
			yyVAL.uint, err = strconv.ParseUint(yyDollar[1].item.Val, 10, 64)
			if err != nil {
				yylex.(*parser).addParseErrf(yyDollar[1].item.PositionRange(), "invalid repetition in series values: %s", err)
			}
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:725
		{
			var err error
			yyVAL.duration, err = parseDuration(yyDollar[1].item.Val)
			if err != nil {
				yylex.(*parser).addParseErr(yyDollar[1].item.PositionRange(), err)
			}
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
//line generated_parser.y:736
		{
			yyVAL.node = &StringLiteral{
				Val:      yylex.(*parser).unquoteString(yyDollar[1].item.Val),
				PosRange: yyDollar[1].item.PositionRange(),
			}
		}
	case 196:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:749
		{
			yyVAL.duration = 0
		}
	case 198:
		yyDollar = yyS[yypt-0 : yypt+1]
//line generated_parser.y:753
		{
			yyVAL.strings = nil
		}
	}
	goto yystack /* stack new state and value */
}
